USE cuisine;
CREATE TABLE ingredients (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE recipes (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    instructions TEXT NOT NULL,
    cooking_time INT UNSIGNED NOT NULL,
    servings INT UNSIGNED NOT NULL 
);

CREATE TABLE recipe_ingredients (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    recipe_id INT UNSIGNED NOT NULL,
    ingredient_id INT UNSIGNED NOT NULL,
    quantity VARCHAR(50) NOT NULL,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE
);

CREATE TABLE favorites (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
    session_id VARCHAR(50) NOT NULL, 
    recipe_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE
);
